### PR TITLE
Add OP badge to posts

### LINKED ISSUE #126: display OP badge
show when a post is written by the OP

### PR DESCRIPTION
**Pull request by micahlt**
This resolves #126 by adding a badge beside the username of the thread author.  It works by passing props down two levels.  All components modified were tested and appear to be working.  

**Screenshot**
image

### CODE REVIEW

**Comment by jeffalo** [comment]
LGTM. just one thing, could there be a title attribute on the OP badge, that just explains what it means? something like "Original poster (the creator of the topic)". or if you can phrase that better :P

**Comment by micahlt** [comment]
Oh, right!  Gotcha, I meant to do that.  Just forgot.  Will add in the next 15 minutes

**Comment by micahlt** [comment]
@jeffalo good to go!

**Comment by jeffalo** [comment]
Awesome, thanks!

**Comment by micahlt** [comment]
> Could you please get something similar to nono word´s next release?

I'm assuming you're referring to ScratchAddons.  Where would this feature be added?

**Comment by return-misaPuding** [comment]
yeah, I´m talking about SA (I just wanted to keep this repo scratch-friendly). I think this could be added to the ocular addon

**Pull request merged**
