### PR TITLE
Handle network errors when connecting to ScratchDB

### PR DESCRIPTION
**Pull request by micahlt**
This PR aims to solve #51 by adding a standalone `Error.vue` component.  I also went ahead and `npm audit fix`-ed the dependencies.  This _has_ been tested and the Error component is responsive to mobile and desktop.  Also I made sure to use the right CSS variables so this is themable.  

| Desktop | Mobile |
|---------- |---------|
| image | image |

### CODE REVIEW

**Comment by jeffalo** [comment]
this looks really neat. i'm going to have to do some testing, i'll let you know if there are any upates :)

**Comment by micahlt** [comment]
Awesome, thanks!

**Comment by Weredime** [comment]
@micahlt This should also handle timeouts using AbortController

**Comment by jeffalo** [comment]
hey @micahlt, thanks for the PR and so sorry for the slow response..

would it be possible to sort out these merge conflicts? the error component would be pretty useful for other things too! maybe it might be easier to just resubmit it as a brand new PR?

**Comment by micahlt** [comment]
I can do that!  I'll work on it if I get a chance today.  You're probably right about it needing to be a new PR.  Merge conflicts suck.

**Comment by micahlt** [comment]
@jeffalo I've resolved all the merge conflicts.  Should be good to go!

**Comment by jeffalo** [comment]
Thank you!

**Pull request merged**
