### PR TITLE
Update Loading Text

### PR DESCRIPTION
**Pull request by ScolderCreations**
i felt like there should be more little things there, i added some facts and stuff

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
you're supposed to make prs linked to a related issue tagged with help wanted.

**Comment by ScolderCreations** [comment]
whoops. Sorry.

**Comment by jeffalo** [comment]
i like these

**Comment by ScolderCreations** [comment]
> i like these
Thanks, i might make more another time.

**Comment by RedGuy12** [comment]
Idea:
> commenting "automodmute" mutes you

**Comment by ScolderCreations** [comment]
> Idea:
> 
> > commenting "automodmute" mutes you

A problem with this, is the ST might have the admin panel spammed with people trying this out.

**Comment by jeffalo** [comment]
> > Idea:
> > > commenting "automodmute" mutes you
> 
> A problem with this, is the ST might have the admin panel spammed with people trying this out.

yeah don't do that

**Comment by jeffalo** [comment]
thanks

**Comment by ScolderCreations** [comment]
thanks for the merge! can we close this?

**Pull request merged**
