### PR TITLE
Admin panel 🤩

### PR DESCRIPTION
**Pull request by pufferfish101007**
Makes users list better + allows setting user to edit in daahboard from query param
Bear in mind the saveChanges fn has not been tested, please change it if it's wrong.
Also feel free to change the css
most other stuff has been tested locally

### CODE REVIEW

**Comment by jeffalo** [comment]
thank you for this pull request

**Comment by DragonEggFish** [comment]
omg its real

**Comment by pufferfish101007** [comment]
@jeffalo merge time?

**Comment by return-misaPuding** [comment]
What does "watch" do (I don know JS too much)? Also what does the `adminFeedback()` function do?

**Comment by pufferfish101007** [comment]
> What does "watch" do (I don know JS too much)? 

It's vue - see https://vuejs.org/v2/guide/computed.html#Watchers

> Also what does the `adminFeedback()` function do?

It tells the admin what will happen when they press the update button.

**Pull request merged**
