### PR TITLE
shorten the length limit to 50 and also remove lol from message when not inputting a username as well as finish the gallery

### PR DESCRIPTION
**Pull request by Time-dragon**

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
no

**Review by Time-dragon — COMMENTED** [review]
Well i need to edit now

**Comment by Time-dragon** [comment]
edited

**Comment by Time-dragon** [comment]
fixed gallery bug

**Comment by Time-dragon** [comment]
> no

yes

**Comment by jeffalo** [comment]
i appreciate the PR, but for now i do not plan on implementing any of these changes. thanks for understanding.

**Comment by Time-dragon** [comment]
> i appreciate the PR, but for now i do not plan on implementing any of these changes. thanks for understanding.

No. You merge the PR. Reopen this and merge this.

**Comment by FunctionalMetatable** [comment]
> > i appreciate the PR, but for now i do not plan on implementing any of these changes. thanks for understanding.
> 
> No. You merge the PR. Reopen this and merge this.

That's rude. You don't get what you want always. It's up to the maintainer (@jeffalo) to if he wants to merge it or not. Welcome to the world of pull requests on GitHub.

**Pull request closed without merging**
