### PR TITLE
hope this changes it to barf with pink puffbals

### PR DESCRIPTION
**Pull request by PoIygon**
pls add barf with pink puffballs

### CODE REVIEW

**Comment by FunctionalMetatable** [comment]
it makes ocular look like barf. the normal theme would be gone

**Comment by PoIygon** [comment]
> 
> 
> it makes ocular look like barf. the normal theme would be gone

thats what i wanna do

**Comment by brourbeinsus** [comment]
> > it makes ocular look like barf. the normal theme would be gone
> 
> thats what i wanna do
But whyyyyyyyyyy you could have made it a theme and it would possibly be m e r g e

**Comment by PoIygon** [comment]
> > > it makes ocular look like barf. the normal theme would be gone
> > 
> > 
> > thats what i wanna do
> 
> But whyyyyyyyyyy you could have made it a theme and it would possibly be m e r g e

HOW DO YOU MAKE IT A THEME THEN

**Comment by brourbeinsus** [comment]
> > > > it makes ocular look like barf. the normal theme would be gone
> > > 
> > > 
> > > thats what i wanna do
> > 
> > 
> > But whyyyyyyyyyy you could have made it a theme and it would possibly be m e r g e
> 
> HOW DO YOU MAKE IT A THEME THEN

I DONT KNOW AAAA

**Pull request closed without merging**
