### PR TITLE
You can mention Scratch Addons

### PR DESCRIPTION
**Pull request by Time-dragon**
and also i like how you write, like i am doing right now.

### CODE REVIEW

**Comment by RedGuy12** [comment]
we doesn't want to mention sa because then he can't link to it from scratch

**Comment by FunctionalMetatable** [comment]
what is wrong with you Scratory is styled as Scratory

**Comment by FunctionalMetatable** [comment]
...and now technically jeffalo cannot link to the github pull requests because of you.

**Comment by jeffalo** [comment]
I think I know what I'm allowed to do.

**Pull request closed without merging**
