### PR TITLE
New loading messages!

### PR DESCRIPTION
**Pull request by JaydenDev**
2 new loading messages!

### CODE REVIEW

**Comment by JaydenDev** [comment]
> 
> 
> Pls remove line 64 And 66, 64 is quite long, many ppl already know it and it's not funny and 64 isn't true (I think some backend is closed-source

I applied the requested fixes!

**Comment by JaydenDev** [comment]
Has this PR ever been considered?

**Comment by jeffalo** [comment]
yes, but it looks like there are merge conflicts

**Comment by return-misaPuding** [comment]
IDK, one of my PRs at Magnifier's old repo is still open but it says there are merge conflicts because CluckCluckChicken already removed the frontend ban system, maybe the base isn't up-to-date because of the other loading messages PRs so you could try a rebase (I'm not a git master, but I think it fetches all commits from the main repo and applies them to the fork)

**Comment by JaydenDev** [comment]
Merge Conflicts? Might have to copy and paste the code in instead then.

**Comment by jeffalo** [comment]
thanks, but we really don't need any more loading screen tips right now.

**Pull request closed without merging**
